[tools]
bun = "1.4.2"

[tasks."release:major"]
description = "Create and push a major release"
confirm = "Create and push a major release?"
run = [
	"bun install --frozen-lockfile",
	"bun run format:check",
	"bun run typecheck",
	"bun pm version major",
	"safe-push push --follow-tags",
]

[tasks."release:minor"]
description = "Create and push a minor release"
confirm = "Create and push a minor release?"
run = [
	"bun install --frozen-lockfile",
	"bun run format:check",
	"bun run typecheck",
	"bun pm version minor",
	"safe-push push --follow-tags",
]

[tasks."release:patch"]
description = "Create and push a patch release"
confirm = "Create and push a patch release?"
run = [
	"bun install --frozen-lockfile",
	"bun run format:check",
	"bun run typecheck",
	"bun pm version patch",
	"safe-push push --follow-tags",
]
